### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by TaqueriaVallarta** [TaqueriaVallarta/Flight-Profile#6]
Create a csv export file of values for after the simulation. Some starting points: pandas

**Comment by TaqueriaVallarta** [comment]
It should simply export all of the relevant values: height_agl, height_asl, velocity, acceleration, mass, thrust, drag, air density, air pressure, air temperature, speed of sound, drag coefficient (for when it will change with time)

**Comment by Moizcode** [comment]
So now i added the export csv code to the unstable branch or in the main branch.

**Comment by TaqueriaVallarta** [comment]
Unstable branch please
